dev: false
title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- target
- logs
- templates
ext:
- go
- tmpl
lang: golang
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - gofmt -w ./
  - ps -ef|grep 'network_probe server'| grep -v grep | awk '{print $2}' | sudo xargs kill -9
  after:
  - ps -ef|grep 'network_probe server'| grep -v grep | awk '{print $2}' | sudo xargs kill -9
  - sudo ./network_probe server &
  exit:
  - ps -ef|grep 'network_probe server'| grep -v grep | awk '{print $2}' | sudo xargs kill -9
  - rm -rf ./network_probe
link: https://github.com/midoks/zzz
