dev: true
title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- target
- logs
- templates
ext:
- rs
lang: rust
enablerun: false
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - ps -ef|grep 'network_probe server'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
  - ./target/release/network_probe server --host 0.0.0.0 --port 8080 &
  exit:
  - ps -ef|grep 'network_probe server'| grep -v grep | awk '{print $2}' | xargs kill -9
link: https://github.com/midoks/zzz
